# Generated by Django 6.0.8 on 2026-08-30 07:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('route_description', models.CharField(max_length=200)),
                ('avoids_corridor', models.CharField(max_length=50)),
                ('transit_days', models.IntegerField()),
                ('price_premium_usd', models.FloatField()),
                ('api_gravity', models.FloatField()),
                ('sulfur_pct', models.FloatField()),
                ('sanctioned', models.BooleanField(default=False)),
                ('route_geometry', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('capacity_mbd', models.FloatField()),
                ('transit_days', models.IntegerField()),
                ('baseline_risk', models.FloatField(default=0.1)),
                ('live_risk_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('state', models.CharField(max_length=50)),
                ('throughput_mbd', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=50)),
                ('avg_export_mbd', models.FloatField()),
                ('sanctioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('raw_text', models.TextField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['processed', 'ingested_at'], name='core_rawart_process_68b7d4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Refinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('capacity_mbd', models.FloatField()),
                ('min_run_rate', models.FloatField(default=0.7)),
                ('api_gravity_min', models.FloatField()),
                ('api_gravity_max', models.FloatField()),
                ('sulfur_tolerance', models.FloatField()),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.port')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('sanction', 'Sanction'), ('military', 'Military'), ('shipping', 'Shipping'), ('policy', 'Policy'), ('other', 'Other')], max_length=20)),
                ('severity', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('article_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.corridor')),
            ],
            options={
                'indexes': [models.Index(fields=['corridor', 'timestamp'], name='core_extrac_corrido_cd9e5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('raw_score', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corridor')),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['corridor', 'computed_at'], name='core_risksc_corrido_00bbcb_idx')],
            },
        ),
    ]
