# Generated by Django 6.0.8 on 2026-09-13 07:43

from django.db import migrations, models


def backfill_titles(apps, schema_editor):
    """Copy titles across from RawArticle for events extracted before this field
    existed. Only possible while those staging rows survive (they are deleted at
    14 days), so it runs here rather than being left to a later chore."""
    ExtractedEvent = apps.get_model("core", "ExtractedEvent")
    RawArticle = apps.get_model("core", "RawArticle")

    events = list(ExtractedEvent.objects.filter(title=""))
    if not events:
        return

    titles = dict(
        RawArticle.objects.filter(
            url__in={e.article_url for e in events}
        ).values_list("url", "title")
    )
    for event in events:
        event.title = titles.get(event.article_url, "")
    ExtractedEvent.objects.bulk_update(events, ["title"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedevent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(backfill_titles, migrations.RunPython.noop),
    ]
