# Generated by Django 6.0.8 on 2026-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extractedevent_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativesupplier',
            name='max_incremental_mbd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alternativesupplier',
            name='transits_corridors',
            field=models.JSONField(default=list),
        ),
    ]
