# Generated by Django 6.0.8 on 2026-09-26 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alternativesupplier_transits_and_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('options', models.JSONField(default=dict)),
                ('stages_run', models.JSONField(default=list)),
                ('ingest_report', models.JSONField(blank=True, null=True)),
                ('extraction_report', models.JSONField(blank=True, null=True)),
                ('risk_scores', models.JSONField(default=dict)),
                ('criticality', models.JSONField(default=list)),
                ('threshold', models.JSONField(blank=True, null=True)),
                ('triggered_corridor', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity_loss_mbd', models.FloatField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('errors', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='core_pipeli_started_a40471_idx')],
            },
        ),
    ]
